# Generated by Django 5.0.2 on 2024-03-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_custmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custmer',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
