# Generated by Django 5.0.2 on 2024-03-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_address_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stutas',
            field=models.BooleanField(default=False),
        ),
    ]
